name: Master
on: 
  push:
      branches:
        - master
      paths-ignore:
        - "podcast_audio/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - name: "Install Node Dependencies"
      run: npm ci    
    - name: "Setup Hugo on Runner"
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'
        extended: true
    - name: "Replace tokens in Configuration"
      uses: cschleiden/replace-tokens@v1.0
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '["config.yaml"]'
      env:
        hostname: 'https://www.cloudwithchris.com/'
    - name: "Build and Minify Hugo Contents"
      run: hugo --minify    
    - name: "Upload Generated Static Content as Website Artifact"
      uses: actions/upload-artifact@v1
      with:
        name: website
        path: ${{ github.workspace }}/public
  publish:    
    environment:
      name: production.azure
      url: https://www.cloudwithchris.com  
    runs-on: ubuntu-latest
    needs: build
    steps:    
    - name: "Download Website Artifact"
      uses: actions/download-artifact@v1
      with:
        name: website
    - name: "Login to Azure"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}     
    - name: "Upload Static Content to Storage"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob upload-batch --account-name cloudwithchrisprod -d '$web' -s website
    - name: "Purge CDN"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "cloudwithchris" --name "cloudwithchris" --resource-group "cloudwithchris"
