name: "Podcast Audio Upload"
on: 
  push:
      branches:
        - master
      paths:
        - "podcast_audio/**"
jobs:
  publish:    
    environment:
      name: production.azure
      url: https://www.cloudwithchris.com  
    runs-on: ubuntu-latest
    steps:    
    - name: Download Podcast
      run: |
        pwd
        git clone --config lfs.fetchexclude="/podcast_audio" https://github.com/chrisreddington/cloudwithchris.com.git ./
        ls -la
        filechanged=`git diff --name-only HEAD^ HEAD -- '*.mp3'`
        echo "PODCAST_AUDIO_LOCATION=$GITHUB_WORKSPACE/$filechanged" >> $GITHUB_ENV
        echo "PODCAST_AUDIO_BLOB=${filechanged/podcast_audio\//''}" >> $GITHUB_ENV
        rm ./$filechanged
        git config --unset lfs.fetchexclude
        git checkout . 
        cd podcast_audio
        pwd
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}     
    - name: "Upload podcast files to storage that don't yet exist"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.20.0
        inlineScript: |
          az storage blob upload --account-name cloudwithchrisprod -c 'podcasts' --file ${{ env.PODCAST_AUDIO_LOCATION }} -n ${{ env.PODCAST_AUDIO_BLOB }} --if-unmodified-since 2020-01-01T00:00Z
